canal.instance.mysql.slaveId=1001
canal.instance.master.address=host.docker.internal:3306
#??? Canal ????????? MySQL?
#?? Canal ? Docker ??????? localhost:3306??????????????
host.docker.internal:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
#????
canal.instance.connectionCharset=UTF-8
canal.instance.defaultDatabaseName=demo1
canal.instance.enableDruid=false
canal.instance.gtidon=false

canal.instance.filter.regex=demo1\\.outbox
#??outbox?
canal.instance.filter.black.regex=mysql\\..*,information_schema\\..*,performance_schema\\..*,sys\\..*
